version: 0.2

phases:
  install:
    commands:
      - dotnet restore
  build:
    commands:
      - dotnet build hello-world-api/hello-world-api.csproj
  post_build:
    commands:
      - dotnet publish -c Release -o ./publish
artifacts:
  files:
    - '*/'
